{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "cef1afa7",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/var/folders/rs/bwptk0k17bq61j_mw_gqdpg00000gn/T/ipykernel_46062/2720928999.py:3: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.\n",
      "\n",
      "\n",
      "  dataframe=pd.read_csv(url, error_bad_lines=False)\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Unnamed: 0</th>\n",
       "      <th>RMSE</th>\n",
       "      <th>QLIKE</th>\n",
       "      <th>MAE</th>\n",
       "      <th>n_inputs</th>\n",
       "      <th>mlp_units</th>\n",
       "      <th>epochs</th>\n",
       "      <th>learning_rate</th>\n",
       "      <th>num_lr_decays</th>\n",
       "      <th>scaler_type</th>\n",
       "      <th>dropout</th>\n",
       "      <th>n_pool_kernel_size</th>\n",
       "      <th>pooling_mode</th>\n",
       "      <th>interpolation_mode</th>\n",
       "      <th>n_blocks</th>\n",
       "      <th>random_seed</th>\n",
       "      <th>trial</th>\n",
       "      <th>id_H</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>0</td>\n",
       "      <td>0.648719</td>\n",
       "      <td>0.002187</td>\n",
       "      <td>0.534285</td>\n",
       "      <td>10</td>\n",
       "      <td>[512, 512]</td>\n",
       "      <td>450</td>\n",
       "      <td>0.00001</td>\n",
       "      <td>1</td>\n",
       "      <td>minmax</td>\n",
       "      <td>0.2</td>\n",
       "      <td>2</td>\n",
       "      <td>AvgPool1d</td>\n",
       "      <td>nearest</td>\n",
       "      <td>1</td>\n",
       "      <td>21170174</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>1</td>\n",
       "      <td>0.651947</td>\n",
       "      <td>0.002203</td>\n",
       "      <td>0.548189</td>\n",
       "      <td>21</td>\n",
       "      <td>[250, 250]</td>\n",
       "      <td>100</td>\n",
       "      <td>0.00005</td>\n",
       "      <td>2</td>\n",
       "      <td>minmax</td>\n",
       "      <td>0.2</td>\n",
       "      <td>2</td>\n",
       "      <td>MaxPool1d</td>\n",
       "      <td>linear</td>\n",
       "      <td>2</td>\n",
       "      <td>53068056</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>2</td>\n",
       "      <td>0.582363</td>\n",
       "      <td>0.001730</td>\n",
       "      <td>0.464713</td>\n",
       "      <td>15</td>\n",
       "      <td>[250, 250]</td>\n",
       "      <td>750</td>\n",
       "      <td>0.00005</td>\n",
       "      <td>2</td>\n",
       "      <td>minmax</td>\n",
       "      <td>0.2</td>\n",
       "      <td>2</td>\n",
       "      <td>MaxPool1d</td>\n",
       "      <td>linear</td>\n",
       "      <td>1</td>\n",
       "      <td>114940090</td>\n",
       "      <td>2</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>3</td>\n",
       "      <td>0.648014</td>\n",
       "      <td>0.002226</td>\n",
       "      <td>0.534159</td>\n",
       "      <td>84</td>\n",
       "      <td>[712, 712]</td>\n",
       "      <td>650</td>\n",
       "      <td>0.00005</td>\n",
       "      <td>2</td>\n",
       "      <td>minmax</td>\n",
       "      <td>0.4</td>\n",
       "      <td>2</td>\n",
       "      <td>AvgPool1d</td>\n",
       "      <td>nearest</td>\n",
       "      <td>2</td>\n",
       "      <td>81839022</td>\n",
       "      <td>3</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>4</td>\n",
       "      <td>0.704002</td>\n",
       "      <td>0.002632</td>\n",
       "      <td>0.578847</td>\n",
       "      <td>10</td>\n",
       "      <td>[712, 712]</td>\n",
       "      <td>750</td>\n",
       "      <td>0.00010</td>\n",
       "      <td>3</td>\n",
       "      <td>minmax</td>\n",
       "      <td>0.0</td>\n",
       "      <td>2</td>\n",
       "      <td>AvgPool1d</td>\n",
       "      <td>nearest</td>\n",
       "      <td>2</td>\n",
       "      <td>51504931</td>\n",
       "      <td>4</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>115</th>\n",
       "      <td>25</td>\n",
       "      <td>0.560285</td>\n",
       "      <td>0.001626</td>\n",
       "      <td>0.444642</td>\n",
       "      <td>10</td>\n",
       "      <td>[250, 250]</td>\n",
       "      <td>550</td>\n",
       "      <td>0.00005</td>\n",
       "      <td>2</td>\n",
       "      <td>standard</td>\n",
       "      <td>0.2</td>\n",
       "      <td>1</td>\n",
       "      <td>MaxPool1d</td>\n",
       "      <td>linear</td>\n",
       "      <td>5</td>\n",
       "      <td>26037775</td>\n",
       "      <td>25</td>\n",
       "      <td>4</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>116</th>\n",
       "      <td>26</td>\n",
       "      <td>0.648281</td>\n",
       "      <td>0.002153</td>\n",
       "      <td>0.514662</td>\n",
       "      <td>21</td>\n",
       "      <td>[250, 250]</td>\n",
       "      <td>100</td>\n",
       "      <td>0.00001</td>\n",
       "      <td>1</td>\n",
       "      <td>standard</td>\n",
       "      <td>0.0</td>\n",
       "      <td>1</td>\n",
       "      <td>MaxPool1d</td>\n",
       "      <td>linear</td>\n",
       "      <td>3</td>\n",
       "      <td>41165234</td>\n",
       "      <td>26</td>\n",
       "      <td>4</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>117</th>\n",
       "      <td>27</td>\n",
       "      <td>0.678089</td>\n",
       "      <td>0.002352</td>\n",
       "      <td>0.550407</td>\n",
       "      <td>15</td>\n",
       "      <td>[712, 712]</td>\n",
       "      <td>50</td>\n",
       "      <td>0.00010</td>\n",
       "      <td>3</td>\n",
       "      <td>robust</td>\n",
       "      <td>0.2</td>\n",
       "      <td>0</td>\n",
       "      <td>MaxPool1d</td>\n",
       "      <td>linear</td>\n",
       "      <td>3</td>\n",
       "      <td>66194025</td>\n",
       "      <td>27</td>\n",
       "      <td>4</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>118</th>\n",
       "      <td>28</td>\n",
       "      <td>0.763466</td>\n",
       "      <td>0.002919</td>\n",
       "      <td>0.655210</td>\n",
       "      <td>42</td>\n",
       "      <td>[512, 512]</td>\n",
       "      <td>350</td>\n",
       "      <td>0.00010</td>\n",
       "      <td>3</td>\n",
       "      <td>minmax</td>\n",
       "      <td>0.2</td>\n",
       "      <td>2</td>\n",
       "      <td>MaxPool1d</td>\n",
       "      <td>linear</td>\n",
       "      <td>1</td>\n",
       "      <td>122236069</td>\n",
       "      <td>28</td>\n",
       "      <td>4</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>119</th>\n",
       "      <td>29</td>\n",
       "      <td>0.737194</td>\n",
       "      <td>0.002691</td>\n",
       "      <td>0.573656</td>\n",
       "      <td>10</td>\n",
       "      <td>[712, 712]</td>\n",
       "      <td>550</td>\n",
       "      <td>0.00010</td>\n",
       "      <td>3</td>\n",
       "      <td>minmax</td>\n",
       "      <td>0.3</td>\n",
       "      <td>2</td>\n",
       "      <td>AvgPool1d</td>\n",
       "      <td>nearest</td>\n",
       "      <td>5</td>\n",
       "      <td>22922777</td>\n",
       "      <td>29</td>\n",
       "      <td>4</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>120 rows × 18 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "     Unnamed: 0      RMSE     QLIKE       MAE  n_inputs   mlp_units  epochs  \\\n",
       "0             0  0.648719  0.002187  0.534285        10  [512, 512]     450   \n",
       "1             1  0.651947  0.002203  0.548189        21  [250, 250]     100   \n",
       "2             2  0.582363  0.001730  0.464713        15  [250, 250]     750   \n",
       "3             3  0.648014  0.002226  0.534159        84  [712, 712]     650   \n",
       "4             4  0.704002  0.002632  0.578847        10  [712, 712]     750   \n",
       "..          ...       ...       ...       ...       ...         ...     ...   \n",
       "115          25  0.560285  0.001626  0.444642        10  [250, 250]     550   \n",
       "116          26  0.648281  0.002153  0.514662        21  [250, 250]     100   \n",
       "117          27  0.678089  0.002352  0.550407        15  [712, 712]      50   \n",
       "118          28  0.763466  0.002919  0.655210        42  [512, 512]     350   \n",
       "119          29  0.737194  0.002691  0.573656        10  [712, 712]     550   \n",
       "\n",
       "     learning_rate  num_lr_decays scaler_type  dropout  n_pool_kernel_size  \\\n",
       "0          0.00001              1      minmax      0.2                   2   \n",
       "1          0.00005              2      minmax      0.2                   2   \n",
       "2          0.00005              2      minmax      0.2                   2   \n",
       "3          0.00005              2      minmax      0.4                   2   \n",
       "4          0.00010              3      minmax      0.0                   2   \n",
       "..             ...            ...         ...      ...                 ...   \n",
       "115        0.00005              2    standard      0.2                   1   \n",
       "116        0.00001              1    standard      0.0                   1   \n",
       "117        0.00010              3      robust      0.2                   0   \n",
       "118        0.00010              3      minmax      0.2                   2   \n",
       "119        0.00010              3      minmax      0.3                   2   \n",
       "\n",
       "    pooling_mode interpolation_mode  n_blocks  random_seed  trial  id_H  \n",
       "0      AvgPool1d            nearest         1     21170174      0     1  \n",
       "1      MaxPool1d             linear         2     53068056      1     1  \n",
       "2      MaxPool1d             linear         1    114940090      2     1  \n",
       "3      AvgPool1d            nearest         2     81839022      3     1  \n",
       "4      AvgPool1d            nearest         2     51504931      4     1  \n",
       "..           ...                ...       ...          ...    ...   ...  \n",
       "115    MaxPool1d             linear         5     26037775     25     4  \n",
       "116    MaxPool1d             linear         3     41165234     26     4  \n",
       "117    MaxPool1d             linear         3     66194025     27     4  \n",
       "118    MaxPool1d             linear         1    122236069     28     4  \n",
       "119    AvgPool1d            nearest         5     22922777     29     4  \n",
       "\n",
       "[120 rows x 18 columns]"
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import pandas as pd\n",
    "url=\"RMSE_comparison.csv\"\n",
    "dataframe=pd.read_csv(url, error_bad_lines=False)\n",
    "dataframe"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "42a48f2a",
   "metadata": {},
   "outputs": [],
   "source": [
    "from dash import Dash, html, dcc, callback, Output, Input\n",
    "import plotly.express as px\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "app = Dash(__name__)\n",
    "server= app.server\n",
    "app.layout = html.Div([\n",
    "    html.H1(children='RMSE comparison', style={'textAlign':'center'}),\n",
    "    dcc.Dropdown(dataframe.id_H.unique(), '1', id='dropdown-selection'),\n",
    "    dcc.Graph(id='graph-content')\n",
    "])\n",
    "\n",
    "@callback(\n",
    "    Output('graph-content', 'figure'),\n",
    "    Input('dropdown-selection', 'value')\n",
    ")\n",
    "def update_graph(value):\n",
    "    record = dataframe[dataframe.id_H==value]\n",
    "    return px.bar(record,x='trial', y='RMSE',hover_data=['n_inputs', 'mlp_units', 'scaler_type', 'dropout', 'n_pool_kernel_size', 'pooling_mode', 'interpolation_mode', 'n_blocks'],color='scaler_type', title='RMSE comparison', orientation='v' )\n",
    "\n",
    "if __name__ == '__main__':\n",
    "    app.run(debug=True)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
